buildscript {
    repositories {
        mavenCentral()
        maven {url = "http://files.minecraftforge.net/maven"}
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'


version = "1.12.2-1.2.5"
group= "shadows.endertweaker"
archivesBaseName = "EnderTweaker"

sourceCompatibility = targetCompatibility = "1.8"
compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "stable_39"
	makeObfSourceJar = false
}

repositories {
    maven {
        url "http://dvs1.progwml6.com/files/maven"
    }
	maven {
		url "http://maven.tterrag.com"
	}
	maven {
		url 'http://maven.blamejared.com'
	}
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
	deobfCompile "mezz.jei:jei_1.12.2:+"
    deobfCompile "curse.maven:the-one-probe-245211:2667280"
    deobfCompile "curse.maven:enderio-5.3.72-64578:4674244"
    deobfCompile "curse.maven:endercore-0.5.78-231868:4671384"
	deobfCompile "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.+"
}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
