name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Read gradle.properties
        uses: BrycensRanch/read-properties-action@v1
        id: properties
        with:
          file: gradle.properties
          all: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            java-version: "25"
            distribution: "temurin"
            cache: gradle

      - name: Build
        run: ./gradlew build

      - name: Publish to CurseForge
        if: steps.properties.outputs.publish_to_curseforge == 'true'
        uses: gradle/gradle-build-action@v2
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        with:
          arguments: curseforge

      - name: Publish to Modrinth
        if: steps.properties.outputs.publish_to_modrinth == 'true'
        uses: gradle/gradle-build-action@v2
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          arguments: modrinth

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          body: ${{ steps.changelog_reader.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
